PATH OF DATASET:
/home/action/arjsto/Subject01.ds


NUMBER OF CLASSES:
1


CLASSGROUPID:
3
NAME:
BAD
COMMENT:

COLOR:
Red
EDITABLE:
Yes
CLASSID:
1
NUMBER OF TRIALS:
12
LIST OF TRIALS:
TRIAL NUMBER
                  +9
                 +18
                 +84
                +106
                +121
                +125
                +151
                +159
                +186
                +212
                +254
                +259


